### PR TITLE
Fix UART3 on lpc176x, ie: BTT SKR 1.4, BTT SKR 1.4 TURBO

### PR DESCRIPTION
**Pull request by Minims**
Fix UART3 on SKR Board with lpc1768 and lpc1769
look @ https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues/221

### CODE REVIEW

**Comment by p3p** [comment]
Although this works around an issue on those specific boards, changing the default pins associated with the UART3 peripheral changes the behaviour that may be assumed by other boards, to fix this properly a way to configure this will need to be added.

**Comment by ruedli** [comment]
> a way to configure this will need to be added.

Correct, the pins can have 4 functions, selected by Funcnum 0..3, but these functions cannot be selected from Marlin config files as far as I know:

image

**Comment by ruedli** [comment]
Basically, functions are multiplexed to many pins. In the case of UART3 Pin 46/47 under Funcnum 2
image


 and also Pin 7/6:
image

finally Pin 82/85:
image

The last one is used by Bigtreetech.

**Comment by p3p** [comment]
#41 merged

**Pull request closed without merging**
